### ISSUE TITLE
CQM-119: Provide .snapshot folder remove tool.

### ISSUE THREAD

**Issue by maly-admin** [Cognifide/CQ-Unix-Toolkit#7]
Please provide option or another tool used to remove folder ".snapshot".

**Comment by kitarek** [comment]
Tested on:

- Windows (bash)
- FreeBSD (cash)
- Linux (bash)

**Comment by kitarek** [comment]
Tool is tested after bugfixes on:

* Windows/cygwin/bash
* Linux/bash
* FreeBSD/csh

**Comment by kitarek** [comment]
Merged into `1.2-dev`
